name: Daily Sync ARC01 SQLite

on:
  workflow_dispatch: {}
  schedule:
    # 00:00 ICT (UTC+7) = 17:00 UTC ของวันก่อนหน้า
    - cron: "0 17 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: arc01-sqlite-daily
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run sync
        env:
          API_BASE: https://archcu-digitaltwin.mamgistics.com
          DB_PATH: arc01.db
        run: |
          python scripts/sync_sqlite_raw.py

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(sqlite): daily raw sync at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
